- name: This playbook is to set up the kubernetes worker node
  hosts: cluster
  gather_facts: no
  become: yes
  tasks:
  - name: import varaibles
    include_vars: vars/vpc_setup

  - name: import varaibles
    include_vars: vars/output-vars

  - name: import varaibles
    include_vars: vars/hostips
  
  - name: disable swapp
    shell: swapoff -a
    args:
     removes: swap.txt

  - name: Copy script to nodes
    copy:
      src: templates/cont.sh
      dest: /home/ubuntu/cont.sh
      mode: '0755'

  - name: Execute script file on remote host
    script: /home/ubuntu/cont.sh 
    args:
      exeutable: /bin/bash
      removes: cri.txt

  - name: Copy script to nodes
    copy:
      src: templates/kube.sh
      dest: /home/ubuntu/kube.sh
      mode: '0755'

  - name: Execute script file on remote host
    script: /home/ubuntu/kube.sh
    args:
      exeutable: /bin/bash
      removes: kube.txt 


- name: This playbook is to set up the kubernetes worker node
  hosts: mastergrp
  gather_facts: no
  become: yes
  tasks:
  - name: Initialize Kubernetes cluster
    command: kubeadm init
    args:
      removes: kube.yxy

  - name: creat .kube directory
    file:
      path: /home/ubuntu/.kube
      state: directory
        
  - name: Copy kube config file to home directory
    copy: 
      src: /etc/kubernetes/admin.conf
      dest: /home/ubuntu/.kube/config
      mode: 0755
      owner: ubuntu
      group: ubuntu
      remote_src: yes

  - name: ste host name
    command: sudo hostnamectl set-hostname master
