- name: This playbook is to set up the kubernetes worker node
  hosts: cluster
  gather_facts: no
  become: yes
  tasks:
  - name: import varaibles
    include_vars: vars/vpc_setup

  - name: import varaibles
    include_vars: vars/output-vars

  - name: import varaibles
    include_vars: vars/hostips
  
  - name: disable swapp
    shell: swapoff -a
    args:
     creates: swap.txt

  - name: Copy script to nodes
    copy:
      src: templates/cont.sh
      dest: /home/ubuntu/cont.sh
      mode: '0755'

  - name: Execute script file on remote host
    script: /home/ubuntu/cont.sh 
    args:
      exeutable: /bin/bash

  - name: Copy script to nodes
    copy:
      src: templates/kube.sh
      dest: /home/ubuntu/kube.sh
      mode: '0755'

  - name: Execute script file on remote host
    script: /home/ubuntu/kube.sh
    args:
      exeutable: /bin/bash 
