- name: This playbook is to set up the kubernetes worker node
  hosts: cluster
  gather_facts: no
  become: yes
  tasks:
  - name: import varaibles
    include_vars: vars/vpc_setup

  - name: import varaibles
    include_vars: vars/output-vars

  - name: import varaibles
    include_vars: vars/hostips
  
  - name: disable swapp
    shell: swapoff -a
    args:
     creates: swap.txt

  - 
