- name: This playbook is to set up the kubernetes worker node
  hosts: cluster
  gather_facts: no
  become: yes
  tasks:
  - name: import varaibles
    include_vars: vars/vpc_setup

  - name: import varaibles
    include_vars: vars/output-vars

  - name: import varaibles
    include_vars: vars/hostips
  
  - name: disable swapp
    shell: swapoff -a
    args:
      creates: /home/ubuntu/cont.sh

  - name: Copy script to nodes
    copy:
      src: templates/cont.sh
      dest: /home/ubuntu/cont.sh
      mode: '0755'

  - name: Execute script file on remote host
    script: /home/ubuntu/cont.sh >> done.sh
    args:
      exeutable: /bin/bash
      creates: /home/ubuntu/done.sh

  - name: Copy script for installing kubeadm, kubectl and kubelet to  nodes
    copy:
      src: templates/kube.sh
      dest: /home/ubuntu/kube.sh
      mode: '0755'

  - name: Execute script file for installing kubeadm, kubectl and kubelet on remote host
    script: /home/ubuntu/kube.sh >> done.txt
    args:
      exeutable: /bin/bash
      creates: /home/ubuntu/done.txt


- name: This playbook is to set up the kubernetes worker node
  hosts: mastergrp
  gather_facts: false
  become: yes
  tasks:
  - name: Initialize Kubernetes cluster
    shell: kubeadm init >> k8s.txt
    args:
      creates: /home/ubuntu/k8s.txt
  

  - name: creat .kube directory
    file:
      path: /home/ubuntu/.kube
      state: directory
      mode: 0755
        
  - name: Copy kube config file to home directory
    copy: 
      src: /etc/kubernetes/admin.conf
      dest: /home/ubuntu/.kube/config
      mode: 0755
      owner: ubuntu
      group: ubuntu
      remote_src: yes

  - name: set host name
    shell:  hostnamectl set-hostname master>> /home/ubuntu/host.txt
    args:
      creates: /home/ubuntu/host.txt 

  - name: install pod network add on
    shell: wget https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
    args:
      creates: weave-daemonset-k8s.yaml

  - name: Apply weavenet configuration file
    shell: kubectl apply -f weave-daemonset-k8s.yaml >> pre.txt
    remote_src: yes
    args:
      creates: pre.txt