--- 
- name: creating of Vpc and subnets
  hosts: localhost
  gather_facts: false
  connection: loca
  tasks:
  - name: Importing Variables
    include_vars: vars/vpc_setup

  - name:  Create VPC
    ec2_vpc_net:
      name: "{{vpc_name}}"
      cidr_block: "{{vpc_cidr}}"
      region: "{{region}}"
      tags:
        project: k8s
      tenancy: default
      dns_hostnames: yes
      dns_support: yes
      state: "{{state}}"
    register: vpcout

  - name: print output
    debug:
      var: vpcout

